import type { Station } from './types.js'

export const stations = [
  {
    id: 'yunwu',
    name: 'Yunwu',
    homepage: 'https://yunwu.ai',
    i18nNames: { 'zh-CN': '云雾' },
    system: 'new-api',
    supportsInvoice: true,
    supportsCorporateTransfer: true,
    statusUrl: 'https://yunwu.ai/console',
    privacyUrl: false,
    refundUrl: false,
    updatedAt: '2026-05-31'
  },
  {
    id: 'packycode',
    name: 'Packy',
    homepage: 'https://www.packyapi.com',
    system: 'new-api',
    supportsInvoice: false,
    supportsCorporateTransfer: true,
    statusUrl: 'https://check.linux.do/group/Packy',
    privacyUrl: 'https://www.packyapi.com/terms',
    refundUrl: 'https://www.packyapi.com/terms',
    updatedAt: '2026-05-31',
  },
  {
    id: 'ikuncode',
    name: 'IKun Code',
    homepage: 'https://api.ikuncode.cc',
    system: 'new-api',
    statusUrl: 'https://status.ikuncode.cc/',
    privacyUrl: false,
    refundUrl: 'https://docs.ikuncode.cc/support/faq#are-refunds-supported',
    updatedAt: '2026-05-31',
  },
  {
    id: 'bestai',
    name: 'BEST AI',
    homepage: 'https://api.oaibest.com',
    system: 'new-api',
    statusUrl: 'https://status.oaibest.com/status/ai',
    privacyUrl: 'https://api.oaibest.com/privacy-policy',
    refundUrl: false,
    updatedAt: '2026-05-31',
  },
  {
    id: 'duckcoding',
    name: 'Duck Coding',
    homepage: 'https://duckcoding.com',
    system: 'new-api',
    statusUrl: 'https://status.duckcoding.ai/status/duckcoding',
    privacyUrl: 'https://docs.duckcoding.ai/legal/%E9%9A%90%E7%A7%81%E6%94%BF%E7%AD%96.html',
    refundUrl: 'https://docs.duckcoding.ai/legal/%E6%9C%8D%E5%8A%A1%E6%9D%A1%E6%AC%BE.html#s7',
    updatedAt: '2026-05-31',
  },
  {
    id: 'vapi',
    name: 'V-API',
    homepage: 'https://api.v3.cm',
    statusUrl: false,
    privacyUrl: 'https://api.v3.cm/privacy-policy.html',
    refundUrl: 'https://api.v3.cm/license.html',
    updatedAt: '2026-05-31',
  },
  {
    id: 'qianduoduo',
    name: 'Qianduoduo',
    homepage: 'https://api2.aigcbest.top',
    i18nNames: { 'zh-CN': '钱多多' },
    system: 'new-api',
    statusUrl: false,
    privacyUrl: false,
    refundUrl: false,
    updatedAt: '2026-05-31',
  },
  {
    id: 'dmxapi',
    name: 'DMX',
    homepage: 'https://www.dmxapi.com',
    system: 'new-api',
    statusUrl: 'https://jk.dmxapi.cn/status/dmxapi',
    privacyUrl: 'https://dmxapi.com/yinsi.html',
    refundUrl: false,
    updatedAt: '2026-05-31',
  },
  {
    id: 'zetatechs',
    name: 'ZetaTechs',
    homepage: 'https://api.zetatechs.com',
    system: 'new-api',
    statusUrl: false,
    privacyUrl: 'https://api.zetatechs.com/privacy-policy',
    refundUrl: 'https://api.zetatechs.com/user-agreement',
    updatedAt: '2026-05-31',
  },
  {
    id: 'aihubmix',
    name: 'AIHubMix',
    homepage: 'https://aihubmix.com',
    system: 'custom',
    statusUrl: false,
    privacyUrl: 'https://docs.aihubmix.com/en/api/Data-Pravicy',
    refundUrl: 'https://docs.aihubmix.com/en/terms-and-privacy/Terms#5-4-refund-policy',
    updatedAt: '2026-05-31',
  },
  {
    id: 'cubence',
    name: 'Cubence',
    homepage: 'https://cubence.com',
    system: 'custom',
    statusUrl: 'https://check.linux.do/group/Cubence',
    privacyUrl: 'https://cubence.com/legal/privacy-policy',
    refundUrl: 'https://cubence.com/legal/refund-policy',
    updatedAt: '2026-05-31',
  },
  {
    id: 'aicodemirror',
    name: 'AICodeMirror',
    homepage: 'https://www.aicodemirror.com',
    system: 'custom',
    statusUrl: 'https://status.aicodemirror.com/',
    privacyUrl: false,
    refundUrl: false,
    updatedAt: '2026-05-31',
  },
  {
    id: 'rightcode',
    name: 'Right Code',
    homepage: 'https://www.right.codes',
    system: 'custom',
    statusUrl: 'https://check.linux.do/group/RightCode',
    privacyUrl: false,
    refundUrl: false,
    updatedAt: '2026-05-31',
  },
  {
    id: 'easychat',
    name: 'EasyChat',
    homepage: 'https://easychat.site',
    system: 'custom',
    statusUrl: false,
    privacyUrl: false,
    refundUrl: false,
    updatedAt: '2026-05-31',
  },
  {
    id: 'ccfly',
    name: 'CCFly',
    homepage: 'https://ccfly.codes',
    system: 'custom',
    statusUrl: false,
    privacyUrl: 'https://ccfly.codes/privacy',
    refundUrl: 'https://ccfly.codes/terms',
    updatedAt: '2026-05-31',
  },
  {
    id: 'hongmacc',
    name: 'HongMaCC',
    homepage: 'https://hongmacc.com',
    system: 'custom',
    supportsInvoice: true,
    statusUrl: 'https://hongmacc.com/models',
    privacyUrl: 'https://hongmacc.com/legal/service-specific-terms',
    refundUrl: false,
    updatedAt: "2026-05-31",
  },
  {
    id: 'sssaicode',
    name: 'SSSAICode',
    homepage: 'https://www.sssaicode.com',
    system: 'custom',
    supportsInvoice: false,
    supportsCorporateTransfer: false,
    statusUrl: false,
    privacyUrl: 'https://www.sssaicode.com/terms#privacy',
    refundUrl: 'https://www.sssaicode.com/terms#refund',
    updatedAt: '2026-05-31',
  },
  {
    id: 'cherryin',
    name: 'CherryIN',
    homepage: 'https://open.cherryin.ai',
    system: 'new-api',
    statusUrl: false,
    privacyUrl: 'https://docs.cherryin.ai/en/docs/about/privacy-policy',
    refundUrl: 'https://docs.cherryin.ai/en/docs/about/terms-of-service#5-fees-top-ups-and-refunds',
    updatedAt: '2026-05-31',
  },
  {
    id: '88code',
    name: '88code',
    homepage: 'https://www.88code.ai',
    system: 'custom',
    statusUrl: 'https://www.88code.ai/home-page',
    privacyUrl: false,
    refundUrl:false,
    updatedAt: '2026-05-31',
  },
  {
    id: 'yescode',
    name: 'YesCode',
    homepage: 'https://co.yes.vg',
    system: 'custom',
    statusUrl: 'https://co.yes.vg/provider-status',
    privacyUrl: 'https://co.yes.vg/docs?tab=terms',
    refundUrl: 'https://co.yes.vg/docs?tab=terms',
    updatedAt: '2026-05-31',
  },
  {
    id: 'sparkcode',
    name: 'Spark Code',
    homepage: 'https://www.sparkcode.top/',
    system: 'new-api',
    statusUrl: false,
    privacyUrl: false,
    refundUrl: 'https://www.sparkcode.top/user-agreement',
    updatedAt: '2026-05-31',
  },
  {
    id: 'foxcode',
    name: 'Fox Code',
    homepage: 'https://foxcode.rjj.cc',
    system: 'custom',
    statusUrl: 'https://status.rjj.cc/status/foxcode',
    privacyUrl: false,
    refundUrl: false,
    updatedAt: '2026-05-31',
  },
  {
    id: 'aigocode',
    name: 'AI Go Code',
    homepage: 'https://www.aigocode.com',
    system: 'custom',
    statusUrl: false,
    privacyUrl: 'https://www.aigocode.com/privacy-policy',
    refundUrl: 'https://www.aigocode.com/refund-policy',
    updatedAt: '2026-05-31',
  },
  {
    id: 'claudecn',
    name: 'ClaudeCN',
    homepage: 'https://claudecn.top',
    system: 'custom',
    statusUrl: 'https://claudecn.top/status',
    privacyUrl: false,
    refundUrl: false,
    updatedAt: '2026-05-31',
  },
  {
    id: 'neko',
    name: 'Neko',
    homepage: 'https://nekocode.ai',
    system: 'custom',
    statusUrl: 'https://check.linux.do/group/Neko',
    privacyUrl: false,
    refundUrl: false,
    updatedAt: '2026-05-31',
  },
  {
    id: 'bytecat',
    name: 'ByteCat',
    homepage: 'https://www.bytecatcode.org',
    system: 'new-api',
    openedAt: '2026-01',
    statusUrl: 'https://status.bytecatcode.org/status/bytecat',
    privacyUrl:false,
    refundUrl:false,
    updatedAt: '2026-05-31',
  },
  {
    id: 'tigerapi',
    name: 'Tiger',
    homepage: 'https://tiger.bookapi.cc',
    system: 'new-api',
    statusUrl: false,
    privacyUrl: false,
    refundUrl: false,
    updatedAt: '2026-05-31',
  },
  {
    id: 'monking',
    name: 'Monking',
    homepage: 'https://www.monking.ai',
    system: 'new-api',
    statusUrl: false,
    privacyUrl: false,
    refundUrl: false,
    updatedAt: '2026-05-31',
  },
  {
    id: 'vbcode',
    name: 'VBCode',
    homepage: 'https://vbcode.io',
    system: 'new-api',
    statusUrl: 'https://status.vbcode.io/',
    privacyUrl:false,
    refundUrl:false,
    updatedAt: '2026-05-31',
  },
  {
    id: 'timicc',
    name: 'TiMi CC',
    homepage: 'https://timicc.com',
    system: 'sub2api',
    statusUrl: 'https://status.timicc.com/',
    privacyUrl: 'https://timicc.com/privacy-policy',
    refundUrl:'https://timicc.com/terms-of-service',
    updatedAt: '2026-05-31',
  },
  {
    id: 'apipool',
    name: 'APIPool',
    homepage: 'https://apipool.dev',
    system: 'sub2api',
    statusUrl: false,
    privacyUrl: false,
    refundUrl: false,
    updatedAt: '2026-05-31',
  },
  {
    id: 'bmai',
    name: 'BMAI',
    homepage: 'https://bmai.kun8.vip',
    system: 'sub2api',
    statusUrl: false,
    privacyUrl: false,
    refundUrl: false,
    updatedAt: '2026-05-31',
  },
  {
    id: 'unity2',
    name: 'Unity2',
    homepage: 'https://unity2.ai',
    system: 'sub2api',
    supportsInvoice:true,
    supportsCorporateTransfer:true,
    statusUrl: 'https://status.unity2.ai/',
    privacyUrl: false,
    refundUrl: 'https://icns3iwmxoak.feishu.cn/wiki/AykzwIvToimCUekdd1tcnbo2n3c',
    updatedAt: '2026-05-31',
  },
  {
    id: 'chintao',
    name: 'Chintao',
    homepage: 'https://chintao.cn',
    system: 'new-api',
    statusUrl: false,
    privacyUrl: false,
    refundUrl: false,
    updatedAt: '2026-05-31',
  },
  {
    id: 'xcodebest',
    name: 'Xcode Best',
    homepage: 'https://xcode.best',
    system: 'new-api',
    statusUrl: false,
    privacyUrl: 'https://xcode.best/#privacy',
    refundUrl: 'https://my.feishu.cn/wiki/Re71w4rLUiuZnEkHD2Mc4Pzpndf',
    updatedAt: '2026-05-31',
  },
  {
    id: 'linkapi',
    name: 'LinkAPI',
    homepage: 'https://linkapi.ai',
    system: 'new-api',
    supportsCorporateTransfer: true,
    statusUrl: false,
    privacyUrl: 'https://home.linkapi.ai/privacy.html',
    refundUrl: 'https://home.linkapi.ai/terms.html',
    updatedAt: '2026-05-31',
  },
  {
    id: 'zerocode',
    name: 'ZeroCode',
    homepage: 'https://zerocode.sbs',
    system: 'new-api',
    statusUrl: false,
    privacyUrl: false,
    refundUrl: false,
    updatedAt: '2026-05-31',
  },
  {
    id: 'dawclaudecode',
    name: 'DawCode',
    homepage: 'https://dawclaudecode.com',
    system: 'new-api',
    supportsCorporateTransfer: true,
    statusUrl: false,
    privacyUrl: false,
    refundUrl: false,
    updatedAt: '2026-05-31',
  },
  {
    id: 'jike',
    name: 'JiKe AI',
    homepage: 'https://magic666.top',
    i18nNames: { 'zh-CN': '即刻 AI' },
    system: 'new-api',
    supportsInvoice: false,
    supportsCorporateTransfer: true,
    statusUrl: false,
    privacyUrl: false,
    refundUrl: false,
    updatedAt: '2026-05-31',
  },
  {
    id: 'poloai',
    name: 'PoloAPI',
    homepage: 'https://poloai.top',
    system: 'new-api',
    statusUrl: false,
    privacyUrl: false,
    refundUrl: false,
    updatedAt: '2026-05-31',
  },
  {
    id: 'aiya',
    name: 'AiYa',
    homepage: 'https://api.aiyahmm.com',
    system: 'new-api',
    statusUrl: false,
    privacyUrl: 'https://api.aiyahmm.com/privacy',
    refundUrl: 'https://api.aiyahmm.com/terms',
    updatedAt: '2026-05-31',
  },
  {
    id: '17nas',
    name: '17NAS',
    homepage: 'https://ai.17nas.com',
    i18nNames: { 'zh-CN': '镜核' },
    system: 'new-api',
    statusUrl: 'https://ai.17nas.com/tools/status/',
    privacyUrl: 'https://ai.17nas.com/tools/legal/privacy/',
    refundUrl: false,
    updatedAt: '2026-05-31',
  },
  {
    id: 'buzzai',
    name: 'BUZZ',
    homepage: 'https://buzzai.cc',
    system: 'new-api',
    statusUrl: 'https://buzzai.cc/status',
    privacyUrl: 'https://buzzai.cc/legal/privacy',
    refundUrl: 'https://buzzai.cc/legal/terms#section-3',
    updatedAt: '2026-05-31',
  },
  {
    id: 'doroai',
    name: 'Doro',
    homepage: 'https://us.doro.lol/',
    system: 'new-api',
    statusUrl: false,
    privacyUrl: false,
    refundUrl: false,
    updatedAt: '2026-05-31',
  },
  {
    id: 'aicodingsh',
    name: 'AICoding',
    homepage: 'https://aicoding.sh',
    system: 'custom',
    statusUrl:false,
    privacyUrl:'https://aicoding.sh/en/privacy',
    refundUrl:false,
    updatedAt: '2026-05-31',
  },
  {
    id: 'aiberm',
    name: 'Aiberm',
    homepage: 'https://aiberm.com',
    system: 'new-api',
    statusUrl:false,
    privacyUrl:'https://aiberm.com/privacy',
    refundUrl:'https://aiberm.com/refund',
    updatedAt: '2026-05-31',
  },
  {
    id: 'aimz',
    name: 'AIMZ',
    homepage: 'https://mzlone.top',
    system: 'new-api',
    statusUrl: false,
    privacyUrl: false,
    refundUrl: false,
    updatedAt: '2026-05-31',
  },
  {
    id: '1xm',
    name: 'OneXModel',
    homepage: 'https://1xm.ai',
    system: 'new-api',
    supportsInvoice:true,
    supportsCorporateTransfer:true,
    statusUrl: 'https://1xm.ai/console',
    privacyUrl: 'https://1xm.ai/privacy-policy',
    refundUrl: 'https://1xm.ai/user-agreement',
    updatedAt: '2026-05-31',
  },
  {
    id: 'claude-zhongzhuan',
    name: 'Claude ZZ',
    homepage: 'https://claude-zhongzhuan.cloud',
    system: 'sub2api',
    statusUrl: false,
    privacyUrl: false,
    refundUrl: false,
    updatedAt: '2026-05-31',
  },
  {
    id: 'icodeeasy',
    name: 'I Code Easy',
    homepage: 'https://icodeeasy.cc',
    system: 'custom',
    statusUrl: false,
    privacyUrl: false,
    refundUrl: false,
    updatedAt: '2026-05-31',
  },
  {
    id: 'nowcoding',
    name: 'Now Coding',
    homepage: 'https://nowcoding.ai',
    system: 'new-api',
    statusUrl: 'https://nowcoding.ai/console/service-status',
    privacyUrl:'https://nowcoding.ai/agreement/privacy-policy',
    refundUrl: 'https://nowcoding.ai/agreement/refund-policy',
    updatedAt: '2026-05-31',
  },
  {
    id: 'claude-api-org',
    name: 'Claude API',
    homepage: 'https://claude-api.org',
    system: 'sub2api',
    statusUrl: false,
    privacyUrl:'https://doc.claude-api.org/terms',
    refundUrl:'https://doc.claude-api.org/refund',
    updatedAt: '2026-05-31',
  },
] as const satisfies readonly Station[]
