import type { Station } from './types.js'

export const stations = [
  {
    id: 'yunwu',
    name: 'Yunwu',
    homepage: 'https://yunwu.ai',
    i18nNames: { 'zh-CN': '云雾' },
    system: 'new-api',
  },
  {
    id: 'packycode',
    name: 'Packy',
    homepage: 'https://www.packyapi.com',
    system: 'new-api',
  },
  {
    id: 'ikuncode',
    name: 'IKun Code',
    homepage: 'https://api.ikuncode.cc',
    system: 'new-api',
  },
  {
    id: 'bestai',
    name: 'BEST AI',
    homepage: 'https://api.oaibest.com',
    system: 'new-api',
  },
  {
    id: 'duckcoding',
    name: 'Duck Coding',
    homepage: 'https://duckcoding.com',
    system: 'new-api',
  },
  {
    id: 'vapi',
    name: 'V-API',
    homepage: 'https://api.gpt.ge',
  },
  {
    id: 'qianduoduo',
    name: 'Qianduoduo',
    homepage: 'https://api2.aigcbest.top',
    i18nNames: { 'zh-CN': '钱多多' },
    system: 'new-api',
  },
  {
    id: 'dmxapi',
    name: 'DMX',
    homepage: 'https://www.dmxapi.com',
    system: 'new-api',
  },
  {
    id: 'zetatechs',
    name: 'ZetaTechs',
    homepage: 'https://api.zetatechs.com',
    system: 'new-api',
  },
  {
    id: 'aihubmix',
    name: 'AIHubMix',
    homepage: 'https://aihubmix.com',
    system: 'custom',
  },
  {
    id: 'cubence',
    name: 'Cubence',
    homepage: 'https://cubence.com',
    system: 'custom',
  },
  {
    id: 'aicodemirror',
    name: 'AICodeMirror',
    homepage: 'https://www.aicodemirror.com',
    system: 'custom',
  },
  {
    id: 'rightcode',
    name: 'Right Code',
    homepage: 'https://www.right.codes',
    system: 'custom',
  },
  {
    id: 'easychat',
    name: 'EasyChat',
    homepage: 'https://easychat.site',
    system: 'custom',
  },
  {
    id: 'ccfly',
    name: 'CCFly',
    homepage: 'https://ccfly.codes',
    system: 'custom',
  },
  {
    id: 'hongmacc',
    name: 'HongMaCC',
    homepage: 'https://hongmacc.com',
    system: 'custom',
  },
  {
    id: 'sssaicode',
    name: 'SSSAICode',
    homepage: 'https://www.sssaicode.com',
    system: 'custom',
  },
  {
    id: 'cherryin',
    name: 'CherryIN',
    homepage: 'https://open.cherryin.ai',
    system: 'new-api',
  },
  {
    id: '88code',
    name: '88code',
    homepage: 'https://www.88code.ai',
    system: 'custom',
  },
  {
    id: 'yescode',
    name: 'YesCode',
    homepage: 'https://co.yes.vg',
    system: 'custom',
  },
  {
    id: 'sparkcode',
    name: 'Spark Code',
    homepage: 'https://sparkcode.top',
    system: 'new-api',
  },
  {
    id: 'foxcode',
    name: 'Fox Code',
    homepage: 'https://foxcode.rjj.cc',
    system: 'custom',
  },
  {
    id: 'aigocode',
    name: 'AI Go Code',
    homepage: 'https://www.aigocode.com',
    system: 'custom',
  },
  {
    id: 'claudecn',
    name: 'ClaudeCN',
    homepage: 'https://claudecn.top',
    system: 'custom',
  },
  {
    id: 'neko',
    name: 'Neko',
    homepage: 'https://nekocode.ai',
    system: 'custom',
  },
  {
    id: 'bytecat',
    name: 'ByteCat',
    homepage: 'https://www.bytecatcode.org',
    system: 'new-api',
  },
  {
    id: 'tigerapi',
    name: 'Tiger',
    homepage: 'https://tiger.bookapi.cc',
    system: 'new-api',
  },
  {
    id: 'monking',
    name: 'Monking',
    homepage: 'https://www.monking.ai',
    system: 'new-api',
  },
  {
    id: 'vbcode',
    name: 'VBCode',
    homepage: 'https://vbcode.io',
    system: 'new-api',
  },
  {
    id: 'timicc',
    name: 'TiMi CC',
    homepage: 'https://timicc.com',
    system: 'sub2api',
  },
  {
    id: 'apipool',
    name: 'APIPool',
    homepage: 'https://apipool.dev',
    system: 'sub2api',
  },
  {
    id: 'bmai',
    name: 'BMAI',
    homepage: 'https://bmai.kun8.vip',
    system: 'sub2api',
  },
  {
    id: 'unity2',
    name: 'Unity2',
    homepage: 'https://unity2.ai',
    system: 'sub2api',
  },
  {
    id: 'chintao',
    name: 'Chintao',
    homepage: 'https://chintao.cn',
    system: 'new-api',
  },
  {
    id: 'xcodebest',
    name: 'Xcode Best',
    homepage: 'https://xcode.best',
    system: 'new-api',
  },
  {
    id: 'linkapi',
    name: 'LinkAPI',
    homepage: 'https://linkapi.ai',
    system: 'new-api',
  },
  {
    id: 'zerocode',
    name: 'ZeroCode',
    homepage: 'https://zerocode.sbs',
    system: 'new-api',
  },
  {
    id: 'dawclaudecode',
    name: 'DawCode',
    homepage: 'https://dawclaudecode.com',
    system: 'new-api',
  },
  {
    id: 'jike',
    name: 'JiKe AI',
    homepage: 'https://magic666.top',
    i18nNames: { 'zh-CN': '即刻 AI' },
    system: 'new-api',
  },
  {
    id: 'poloai',
    name: 'PoloAPI',
    homepage: 'https://poloai.top',
    system: 'new-api',
  },
  {
    id: 'aiya',
    name: 'AiYa',
    homepage: 'https://api.aiyahmm.com',
    system: 'new-api',
  },
  {
    id: '17nas',
    name: '17NAS',
    homepage: 'https://ai.17nas.com',
    i18nNames: { 'zh-CN': '镜核' },
    system: 'new-api',
  },
  {
    id: 'buzzai',
    name: 'BUZZ',
    homepage: 'https://buzzai.cc',
    system: 'new-api',
  },
  {
    id: 'doroai',
    name: 'Doro',
    homepage: 'https://doro.lol',
    system: 'new-api',
  },
  {
    id: 'aicodingsh',
    name: 'AICoding',
    homepage: 'https://aicoding.sh',
    system: 'custom',
  },
  {
    id: 'aiberm',
    name: 'Aiberm',
    homepage: 'https://aiberm.com',
    system: 'new-api',
  },
  {
    id: 'aimz',
    name: 'AIMZ',
    homepage: 'https://mzlone.top',
    system: 'new-api',
  },
  {
    id: '1xm',
    name: 'OneXModel',
    homepage: 'https://1xm.ai',
    system: 'new-api',
  },
  {
    id: 'claude-zhongzhuan',
    name: 'Claude ZZ',
    homepage: 'https://claude-zhongzhuan.cloud',
    system: 'sub2api',
  },
  {
    id: 'icodeeasy',
    name: 'I Code Easy',
    homepage: 'https://icodeeasy.cc',
    system: 'custom',
  },
  {
    id: 'nowcoding',
    name: 'Now Coding',
    homepage: 'https://nowcoding.ai',
    system: 'new-api',
  },
  {
    id: 'claude-api-org',
    name: 'Claude API',
    homepage: 'https://claude-api.org',
    system: 'sub2api',
  },
] as const satisfies readonly Station[]
